/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1       */
/*  Created On : 25-may.-2024 08:14:16 p. m.             */
/*  DBMS       : PostgreSQL                              */
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS VIEW_A CASCADE
;

/* Drop Sequences for Autonumber Columns */

/* Drop Tables */

DROP TABLE IF EXISTS Area CASCADE
;

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS Contrato CASCADE
;

DROP TABLE IF EXISTS Espacio CASCADE
;

DROP TABLE IF EXISTS Pago CASCADE
;

DROP TABLE IF EXISTS Parqueadero CASCADE
;

DROP TABLE IF EXISTS Registro CASCADE
;

DROP TABLE IF EXISTS Vehiculo CASCADE
;

DROP TABLE IF EXISTS Vigilante CASCADE
;

/* Create Tables */

CREATE TABLE Area
(
    k_num_area numeric(1) NOT NULL,
    K_iden_parq numeric(4) NOT NULL
)
;

CREATE TABLE Cliente
(
    K_num_iden_cliente numeric(10) NOT NULL,
    K_tipo_iden_cliente varchar(2) NOT NULL,
    N_primer_nom varchar(20) NOT NULL,
    N_segundo_nom_D varchar(20) NULL,
    N_primer_ape varchar(20) NOT NULL,
    N_segundo_ape varchar(20) NULL,
    T_num_contacto numeric(10) NOT NULL
)
;

CREATE TABLE Contrato
(
    K_num_contrato serial NOT NULL,
    V_duracion timestamp without time zone NOT NULL,
    F_horaentrada timestamp without time zone NOT NULL,
    F_horasalida timestamp without time zone NOT NULL,
    V_valor numeric(8) NOT NULL,
    F_fecha_pago date NOT NULL,
    N_estado_contrato varchar(8) NOT NULL,
    K_num_espacio numeric(2) NULL,
    K_placa_veh varchar(6) NULL,
    K_num_iden_cliente numeric(10) NULL,
    K_tipo_iden_prop varchar(2) NULL
)
;

CREATE TABLE Espacio
(
    K_num_espacio numeric(2) NOT NULL,
    V_num_cupos numeric(3) NOT NULL,
    k_num_area numeric(1) NULL,
    K_num_iden_vig numeric(10) NULL,
    K_iden_parq numeric(4) NULL
)
;

CREATE TABLE Pago
(
    K_num_pago serial NOT NULL,
    N_forma_pago varchar(8) NOT NULL,
    V_valor_pagado numeric(8) NOT NULL,
    F_fecha_pago time without time zone NOT NULL,
    K_num_registro numeric(3) NULL
)
;

CREATE TABLE Parqueadero
(
    K_iden_parq numeric(4) NOT NULL,
    V_zona_ciudad numeric(2) NOT NULL,
    V_dir_parqueadero varchar(20) NOT NULL,
    V_nivel_parq numeric(1) NOT NULL,
    I_tipo varchar(10) NOT NULL
)
;

CREATE TABLE Registro
(
    K_num_registro numeric(3) NOT NULL,
    N_placa_registro varchar(6) NOT NULL,
    N_tipo_vehiculo varchar(9) NOT NULL,
    F_hsalida timestamp without time zone NOT NULL,
    F_hentrada timestamp without time zone NOT NULL,
    K_num_espacio numeric(2) NULL
)
;

CREATE TABLE Vehiculo
(
    K_placa_veh varchar(6) NOT NULL,
    N_color_vehiculo varchar(10) NOT NULL,
    N_marca_vehiculo varchar(10) NOT NULL,
    N_modelo_vehiculo varchar(10) NOT NULL,
    N_tipo_vehiculo varchar(10) NOT NULL
)
;

CREATE TABLE Vigilante
(
    K_num_iden_vig numeric(10) NOT NULL,
    K_tipo_iden_vig varchar(2) NOT NULL,
    N_primer_nom varchar(20) NOT NULL,
    N_segundo_nom varchar(20) NULL,
    N_primer_ape varchar(20) NOT NULL,
    N_segundo_ape varchar(20) NULL,
    I_compa_can varchar(1) NOT NULL,
    k_num_area numeric(1) NULL,
    K_iden_parq numeric(4) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Area ADD CONSTRAINT PK_Area
    PRIMARY KEY (k_num_area, K_iden_parq)
;





ALTER TABLE Area ADD CONSTRAINT Ck_num_area CHECK (k_num_area >= 1)
;

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente
    PRIMARY KEY (K_num_iden_cliente, K_tipo_iden_prop)
;

ALTER TABLE Cliente ADD CONSTRAINT CK_tipo_iden_prop CHECK (K_tipo_iden_prop IN ('CC', 'CE'))
;

ALTER TABLE Cliente ADD CONSTRAINT CT_num_contacto CHECK (T_num_contacto >= 0)
;

ALTER TABLE Contrato ADD CONSTRAINT PK_Contrato
    PRIMARY KEY (K_num_contrato)
;

ALTER TABLE Contrato ADD CONSTRAINT CV_valor CHECK (V_valor >= 0)
;

ALTER TABLE Contrato ADD CONSTRAINT CN_estado_contrato CHECK (N_estado_contrato IN ('Activo', 'Inactivo'))
;

ALTER TABLE Espacio ADD CONSTRAINT PK_Espacio
    PRIMARY KEY (K_num_espacio)
;

ALTER TABLE Espacio ADD CONSTRAINT CV_num_cupos CHECK (V_num_cupos >= 0)
;

ALTER TABLE Espacio ADD CONSTRAINT CK_num_espacio CHECK (K_num_espacio >= 1)
;

ALTER TABLE Pago ADD CONSTRAINT PK_Pago
    PRIMARY KEY (K_num_pago)
;

ALTER TABLE Pago ADD CONSTRAINT CN_forma_pago CHECK (N_forma_pago IN ('Efectivo', 'Tarjeta'))
;

ALTER TABLE Pago ADD CONSTRAINT CV_valor_pagado CHECK (V_valor_pagado >= 1)
;

ALTER TABLE Parqueadero ADD CONSTRAINT PK_Parqueadero
    PRIMARY KEY (K_iden_parq)
;

ALTER TABLE Parqueadero ADD CONSTRAINT CK_I_tipo CHECK (I_tipo IN ('S', 'A'))
;

ALTER TABLE Parqueadero ADD CONSTRAINT CK_iden_parq CHECK (K_iden_parq >= 1)
;

ALTER TABLE Parqueadero ADD CONSTRAINT CK_V_nivel_parq CHECK (V_nivel_parq >= 1 AND V_nivel_parq < 10)
;

ALTER TABLE Parqueadero ADD CONSTRAINT CK_V_zona_ciudad CHECK (V_zona_ciudad >= 1)
;

ALTER TABLE Registro ADD CONSTRAINT PK_Registro
    PRIMARY KEY (K_num_registro)
;

ALTER TABLE Registro ADD CONSTRAINT CF_hsalida CHECK (F_hsalida <= now())
;

ALTER TABLE Registro ADD CONSTRAINT CF_hentrada CHECK (F_hentrada <= F_hsalida)
;

ALTER TABLE Registro ADD CONSTRAINT CN_tipo_vehiculo CHECK (N_tipo_vehiculo IN ('Moto', 'Bicicleta', 'carro'))
;

ALTER TABLE Registro ADD CONSTRAINT CK_num_registro CHECK (K_num_registro >= 1)
;

ALTER TABLE Vehiculo ADD CONSTRAINT PK_Vehiculo
    PRIMARY KEY (K_placa_veh)
;

ALTER TABLE Vehiculo ADD CONSTRAINT CN_tipo_vehiculo CHECK (N_tipo_vehiculo IN ('Carro', 'Moto', 'Bicicleta'))
;

ALTER TABLE Vigilante ADD CONSTRAINT PK_Vigilante
    PRIMARY KEY (K_num_iden_vig)
;

ALTER TABLE Vigilante ADD CONSTRAINT CK_tipo_iden_vig CHECK (K_tipo_iden_vig IN ('CC', 'CE'))
;

ALTER TABLE Vigilante ADD CONSTRAINT CK_num_iden_vig CHECK (K_num_iden_vig >= 1)
;

ALTER TABLE Vigilante ADD CONSTRAINT CI_compa_can CHECK (I_compa_can IN ('S', 'N'))
;

/* Create Foreign Key Constraints */

ALTER TABLE Area ADD CONSTRAINT FK_Area_Parqueadero
    FOREIGN KEY (K_iden_parq) REFERENCES Parqueadero (K_iden_parq) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Contrato ADD CONSTRAINT FK_Contrato_Cliente
    FOREIGN KEY (K_num_iden_cliente, K_tipo_iden_prop) REFERENCES Cliente (K_num_iden_cliente, K_tipo_iden_prop) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Contrato ADD CONSTRAINT FK_Contrato_Espacio
    FOREIGN KEY (K_num_espacio) REFERENCES Espacio (K_num_espacio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Contrato ADD CONSTRAINT FK_Contrato_Vehiculo
    FOREIGN KEY (K_placa_veh) REFERENCES Vehiculo (K_placa_veh) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Espacio ADD CONSTRAINT FK_Espacio_Area
    FOREIGN KEY (k_num_area, K_iden_parq) REFERENCES Area (k_num_area, K_iden_parq) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pago ADD CONSTRAINT FK_Pago_Registro
    FOREIGN KEY (K_num_registro) REFERENCES Registro (K_num_registro) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Registro ADD CONSTRAINT FK_Registro_Espacio
    FOREIGN KEY (K_num_espacio) REFERENCES Espacio (K_num_espacio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Vigilante ADD CONSTRAINT FK_Vigilante_Area
    FOREIGN KEY (k_num_area, K_iden_parq) REFERENCES Area (k_num_area, K_iden_parq) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE Parqueadero
    IS 'Almacena la información de los parqueaderos de la ciudad.'
;
